name: Internet.nl monitoring

# notifications are sent to the last user who updated the cron schedule or who last re-enabled the workflow
# https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/notifications-for-workflow-runs

on:
  push:
#  schedule:
    # run every hour
#    - cron: '0 * * * *'

jobs:
  ipv6-test:
    runs-on: ubuntu-latest
    container:
      image: golang:1.21-alpine
      # https://github.com/PowerDNS/pdns/blob/master/.github/workflows/build-and-test-all.yml#L64
      options: --sysctl net.ipv6.conf.all.disable_ipv6=0
    steps:
     - run: apk add curl
     - run: curl -m9 --verbose --ipv6 example.com

  # builds all docker images in parallel
  production:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/internetstandards/test-runner
      # https://github.com/PowerDNS/pdns/blob/master/.github/workflows/build-and-test-all.yml#L64
      options: --sysctl net.ipv6.conf.all.disable_ipv6=0
      env:
        APP_URLS: https://internet.nl
        PY_COLORS: 1
    defaults:
        run:
          working-directory: /source
    steps:
      - name: Run live tests against production
        run:  python3 -m pytest --verbose integration_tests/live/
